<?php
namespace Helper;

// here you can define custom actions
// all public methods declared in helper class will be available in $I
include_once 'BasicHelper.php';
use Codeception\TestInterface;

class Unit extends \Codeception\Module
{
    public function _before(TestInterface $test)
    {
        parent::_before($test); // TODO: Change the autogenerated stub
        $this->includeAll();
    }

    public function includeAll(){
        include_once 'init.php';
    }
}
